name: Trigger Private Repo Job

on:
  schedule:
    - cron: '07 19 * * *'  # 18:00 Israel time (UTC+3)
  workflow_dispatch:

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in private repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_PAT }}" \
            https://api.github.com/repos/hannahbolen/nyisoproject/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
